### PR TITLE
Kiwwa nisa meka daanne

### PR DESCRIPTION
**Pull request by Chamith-Nimmitha**

### CODE REVIEW

**Comment by UdithaIshan** [comment]
palayan yanna

**Comment by Damish-N** [comment]
poddk welaa giyaa bn sorry

**Comment by Chamith-Nimmitha** [comment]
meka mage.. uba palayan

**Comment by Damish-N** [comment]
Gann gann epaa wardim wenwa

**Comment by Damish-N** [comment]
Ubla dennma ayin krnn bri weyid

**Comment by Chamith-Nimmitha** [comment]
pissune bn

**Comment by Chamith-Nimmitha** [comment]
chat box ekak wage dan meka

**Comment by UdithaIshan** [comment]
dihgqc9wagcawhcocoWCWCFWEHOCUFWOCOC

**Pull request merged**
